name: Build and Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build and Upload Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            extra: termux
    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # 3. Install make
      - name: Install Make
        run: sudo apt-get install -y make

      # 4. Set environment variables
      - name: Set Environment Variables
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV
        if: ${{ matrix.extra == 'termux' }}
      
      # 5. Run make build
      - name: Run Make Build
        run: |
          mkdir -p ./bin
          make build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      # 6. Copy configuration files
      - name: Copy Configuration Files
        run: |
          cp ./conf/frpc.toml ./bin/
          cp ./conf/frps.toml ./bin/

      # 7. Zip the output
      - name: Create ZIP Archive
        run: |
          zip -r release-${{ matrix.goos }}-${{ matrix.goarch }}.zip ./bin

      # 8. Upload artifacts to release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          asset_name: release-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          asset_content_type: application/zip
